ALTER TABLE regional_market_comparables
    ADD COLUMN IF NOT EXISTS property_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS beds INTEGER,
    ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;
